import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from '@/app/_components/NavBar';
import Footer from '@/components/Footer';
import { cn } from '@/libs/utils';
import Provider from '@/GlobalStyles/Provider';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={cn('relative h-full font-sans antialiased', inter.className)}>
          <Provider>
            <main className='relative flex flex-col justify-center min-h-screen'>
              <NavBar />

              <div className='flex flex-1'>{children}</div>

              <Footer />
            </main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
